# Generated by Django 5.2 on 2025-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mission_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
