# Generated by Django 5.2 on 2025-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_mission_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(default='E-Rank', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_xp',
            field=models.IntegerField(default=0),
        ),
    ]
