# Generated by Django 5.2 on 2025-04-30 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_dailyusermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusermission',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
